apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: siyam005/micro-reactjs:v1
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: DB_NAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: DB_PASSWORD

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: DB_USER


